name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣  Provision Java (required by Gradle / Android tooling)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: gradle

      # 3️⃣  Install Android SDK components (platform + build-tools)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 29
          build-tools: "29.0.3"
          ndk: "25.2.9519653"

      # 4️⃣  Build the Debug APK
      - name: Build Debug APK
        run: gradle assembleDebug

      # 5️⃣  Upload the resulting APK as a workflow artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
