name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Langkah 1: Mengambil kode dari repositori Anda
    - name: Checkout repository
      uses: actions/checkout@v4

    # Langkah 2: Menjalankan build dengan versi Gradle yang spesifik
    - name: Set up Gradle and Build
      uses: gradle/gradle-build-action@v2
      with:
        # BARIS INI KITA TAMBAHKAN UNTUK MEMPERBAIKI ERROR
        gradle-version: 8.5
        
        # Perintah build tetap sama
        arguments: assembleDebug

    # Langkah 3: Mengunggah file APK yang sudah jadi
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: legenda-tanah-leluhur.apk
        path: app/build/outputs/apk/debug/app-debug.apk
